### ISSUE TITLE
feature request: make it available for form fields as well

### ISSUE THREAD

**Issue by fritzmg** [Craffft/contao-css-style-selector#10]
It would make sense to make the CSS style selector available for form fields as well.

**Comment by thepixture** [comment]
I agree

**Comment by iCodr8** [comment]
Yep, that's a nice idea!

**Comment by iCodr8** [comment]
The feature is implemented.

https://github.com/Craffft/css-style-selector-bundle/releases/tag/1.3.0

**Comment by fritzmg** [comment]
Could you also merge #7 and #8 and create a `1.3.1` release tag? ;)

**Comment by iCodr8** [comment]
No, because this project is only for Contao 3 and won't be supported. Please add your pull requests to this project with Contao 4 support.
https://github.com/Craffft/css-style-selector-bundle

The changes from this ticket are implemented only on the bundle project with Contao 4 support.
