### ISSUE TITLE
Not working on Contao 3.4.4

### ISSUE THREAD

**Issue by Schooott** [Craffft/contao-css-style-selector#3]
No icon
Label texts not working
css selector dropdown not visible

**Comment by iCodr8** [comment]
Welchen Stand hast du getestet? DB Update gemacht? Fehlermeldungen mal aktiviert?

**Comment by Schooott** [comment]
Aktuellen Stand im ER und DB update. Keine Fehlermeldungen was das betrifft.

**Comment by iCodr8** [comment]
Done
e8f18324eac8fc2ee63fc58de6920c8314adf8fa
14d880d0df3ea0bc5fce823e5effb564ad51fcba

**Comment by iCodr8** [comment]
Ist nun im Contao Repo vorhanden.
