### ISSUE TITLE
Für Nachrichten verfügbar machen

### ISSUE THREAD

**Issue by Schooott** [Craffft/contao-css-style-selector#4]
Aktuell bei Nachrichten nicht nutzbar.

**Comment by iCodr8** [comment]
Momentan lässt sich das leider nicht machen, da tl_news erst nach dem CSS Style Selector geladen wird.

**Comment by iCodr8** [comment]
Es ist nun implementiert, aber es geht nur mit Contao 4, wenn man den CSSStyleSelector nach der News Erweiterung im AppKernel registirert.
