### ISSUE TITLE
empty selection allowed

### ISSUE THREAD

**Issue by fritzmg** [Craffft/contao-css-style-selector#9]
If there are no CSS 'styles' available for selection in a page, element or elsewhere, it only shows

`-`

as an available selection. If you click on that, it will add `-` to the selected styles and then if you save, the error message
```
Invalid option value!
```
is shown.

**Comment by iCodr8** [comment]
I think this is a problem of the Contao Core. What do you think?

**Comment by fritzmg** [comment]
I am not sure, I haven't looked into it that much yet.
